### ISSUE TITLE
merge does not work correctly

### ISSUE THREAD

**Issue by charles-cooper** [charles-cooper/eke-accounts#1]
```
$ docker-compose logs -f
Attaching to ekeaccounts_runner_1
runner_1  | Connected.
runner_1  | 1312022
runner_1  | Traceback (most recent call last):
runner_1  |   File "main.py", line 236, in <module>
runner_1  |     run_server()))
runner_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
runner_1  |     return future.result()
runner_1  |   File "main.py", line 130, in poll_blocks
runner_1  |     process_block(c, blk)
runner_1  |   File "main.py", line 54, in process_block
runner_1  |     merge_addresses(c, addrs)
runner_1  |   File "main.py", line 104, in merge_addresses
runner_1  |     assert len(resultset) <= 1, possible_prefixes
runner_1  | AssertionError: ['abandon abandon', 'abandon abandon length', 'abandon abandon length grid', 'abandon abandon length grid rhythm', 'abandon abandon length grid rhythm earth', 'abandon abandon length grid rhythm earth unaware', 'abandon abandon length grid rhythm earth unaware bird', 'abandon abandon length grid rhythm earth unaware bird soon', 'abandon abandon length grid rhythm earth unaware bird soon dry', 'abandon abandon length grid rhythm earth unaware bird soon dry trick', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine spirit', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine spirit mirror']
ekeaccounts_runner_1 exited with code 1
```
```
$ sqlite3 shorthash.db 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> select * from accounts where shorthash in ('abandon abandon', 'abandon abandon length', 'abandon abandon length grid', 'abandon abandon length grid rhythm', 'abandon abandon length grid rhythm earth', 'abandon abandon length grid rhythm earth unaware', 'abandon abandon length grid rhythm earth unaware bird', 'abandon abandon length grid rhythm earth unaware bird soon', 'abandon abandon length grid rhythm earth unaware bird soon dry', 'abandon abandon length grid rhythm earth unaware bird soon dry trick', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine spirit', 'abandon abandon length grid rhythm earth unaware bird soon dry trick express panther shine spirit mirror');
abandon abandon|fan save|abandon abandon|0x00000000Ae6D2Dd2417733BfA7DeDE6AA10efB58
abandon abandon|wreck knife|abandon abandon length|0x0000000083178E9873ce992f73915EEfa3A27aC5
```

**Comment by charles-cooper** [comment]
Resolved in 32dd81cb21f533e2a8015555c27addf884f668e3
