### ISSUE TITLE
Handle address not found cases

### ISSUE THREAD

**Issue by charles-cooper** [charles-cooper/eke-accounts#2]
```
runner_1  | Error handling request
runner_1  | Traceback (most recent call last):
runner_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
runner_1  |     resp = await task
runner_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
runner_1  |     resp = await handler(request)
runner_1  |   File "main.py", line 222, in get_account_by_address
runner_1  |     return web.json_response(dat[0])
runner_1  | IndexError: list index out of range
```
^ results in error 500. should result in 404 not found.

**Comment by charles-cooper** [comment]
Resolved in c44f5c93b971f85afaf00
